### ISSUE TITLE
https://geojson-generator.surge.sh/ is down

### ISSUE THREAD

**Issue by ken-muturi** [erick-otenyo/geojson-random-generator#13]
https://geojson-generator.surge.sh/

stack trace

Object { status: 401, stack: "" }  mapbox-gl.js:521:1204
    fire mapbox-gl.js:521
    loadURL mapbox-gl.js:381
    onload mapbox-gl.js:503

​

**Comment by erick-otenyo** [comment]
Sorry I changed the Mapbox API Key and forgot to update. Should be working now. Just refresh the site / or clear your cache
